import { sql } from "drizzle-orm";
import { integer, jsonb, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";

/** M0 keeps only the database connectivity seam; domain tables start in M1. */
export const healthChecks = pgTable("health_checks", {
  id: uuid("id").defaultRandom().primaryKey(),
  checkedAt: timestamp("checked_at", { withTimezone: true }).notNull().defaultNow(),
});

export const projects = pgTable("projects", {
  id: uuid("id").defaultRandom().primaryKey(),
  slug: text("slug").notNull().unique(),
  name: text("name").notNull(),
  environment: text("environment").notNull(),
  runtimeMode: text("runtime_mode").notNull(),
  healthStrategy: text("health_strategy").notNull(),
  capabilities: jsonb("capabilities").$type<string[]>().notNull().default([]),
  commandDeliveryMode: text("command_delivery_mode").notNull().default("PULL"),
  commandEndpointUrl: text("command_endpoint_url"),
  commandAuthCiphertext: text("command_auth_ciphertext"),
  commandAuthIv: text("command_auth_iv"),
  commandAuthTag: text("command_auth_tag"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  availability: text("availability").notNull().default("UNKNOWN"),
  operationalHealth: text("operational_health").notNull().default("UNKNOWN"),
  lastSeenAt: timestamp("last_seen_at", { withTimezone: true }),
  lastOperationalAt: timestamp("last_operational_at", { withTimezone: true }),
  lastSuccessfulExecutionAt: timestamp("last_successful_execution_at", { withTimezone: true }),
  lastExecutionAt: timestamp("last_execution_at", { withTimezone: true }),
  lastFailureAt: timestamp("last_failure_at", { withTimezone: true }),
  lastErrorSignature: text("last_error_signature"),
  expectedNextExecutionAt: timestamp("expected_next_execution_at", { withTimezone: true }),
  staleAfterSeconds: integer("stale_after_seconds").notNull().default(300),
  offlineAfterSeconds: integer("offline_after_seconds").notNull().default(900),
  expectedIntervalSeconds: integer("expected_interval_seconds"),
  gracePeriodSeconds: integer("grace_period_seconds"),
  criticality: text("criticality").notNull().default("normal"),
  targetRtoMinutes: integer("target_rto_minutes"),
  lastHealthEventAt: timestamp("last_health_event_at", { withTimezone: true }),
});

export const projectCredentials = pgTable(
  "project_credentials",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    projectId: uuid("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
    environment: text("environment").notNull(),
    tokenPrefix: text("token_prefix").notNull(),
    tokenHash: text("token_hash").notNull().unique(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    revokedAt: timestamp("revoked_at", { withTimezone: true }),
    lastUsedAt: timestamp("last_used_at", { withTimezone: true }),
  },
  (table) => ({ projectEnvironmentIdx: uniqueIndex("project_credentials_project_environment_idx").on(table.projectId, table.environment).where(sql`${table.revokedAt} is null`) }),
);

export const events = pgTable("events", {
  id: uuid("id").defaultRandom().primaryKey(),
  eventId: text("event_id").notNull().unique(),
  schemaVersion: integer("schema_version").notNull(),
  projectId: uuid("project_id").notNull().references(() => projects.id),
  environment: text("environment").notNull(),
  type: text("type").notNull(),
  occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull(),
  sequence: text("sequence"),
  data: jsonb("data").notNull(),
  receivedAt: timestamp("received_at", { withTimezone: true }).notNull().defaultNow(),
  processedAt: timestamp("processed_at", { withTimezone: true }),
  processingAttempts: integer("processing_attempts").notNull().default(0),
  processingError: text("processing_error"),
  quarantinedAt: timestamp("quarantined_at", { withTimezone: true }),
  claimToken: text("claim_token"),
  claimedAt: timestamp("claimed_at", { withTimezone: true }),
  claimExpiresAt: timestamp("claim_expires_at", { withTimezone: true }),
});

export const tasks = pgTable(
  "tasks",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    projectId: uuid("project_id").notNull().references(() => projects.id),
    environment: text("environment").notNull(),
    externalTaskId: text("external_task_id").notNull(),
    type: text("type").notNull(),
    status: text("status").notNull(),
    currentAttempt: integer("current_attempt").notNull().default(0),
    currentRunId: text("current_run_id"),
    lastSequence: text("last_sequence"),
    lastError: text("last_error"),
    lastErrorSignature: text("last_error_signature"),
    lastEventAt: timestamp("last_event_at", { withTimezone: true }).notNull(),
    startedAt: timestamp("started_at", { withTimezone: true }),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    metadata: jsonb("metadata").notNull().default({}),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({ taskScopeIdx: uniqueIndex("tasks_project_environment_external_id_idx").on(table.projectId, table.environment, table.externalTaskId) }),
);

export const incidents = pgTable(
  "incidents",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    projectId: uuid("project_id").notNull().references(() => projects.id),
    environment: text("environment").notNull(),
    type: text("type").notNull(),
    dedupKey: text("dedup_key").notNull(),
    severity: text("severity").notNull(),
    state: text("state").notNull().default("OPEN"),
    reason: text("reason").notNull(),
    dependencyKey: text("dependency_key"),
    taskId: text("task_id"),
    errorSignature: text("error_signature"),
    firstSeenAt: timestamp("first_seen_at", { withTimezone: true }).notNull(),
    lastSeenAt: timestamp("last_seen_at", { withTimezone: true }).notNull(),
    occurrenceCount: integer("occurrence_count").notNull().default(1),
    acknowledgedAt: timestamp("acknowledged_at", { withTimezone: true }),
    resolvedAt: timestamp("resolved_at", { withTimezone: true }),
    resolutionReason: text("resolution_reason"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({ incidentDedupIdx: uniqueIndex("incidents_open_dedup_idx").on(table.projectId, table.environment, table.dedupKey, table.state) }),
);

export const incidentEvents = pgTable(
  "incident_events",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    incidentId: uuid("incident_id").notNull().references(() => incidents.id, { onDelete: "cascade" }),
    eventId: uuid("event_id").notNull().references(() => events.id, { onDelete: "cascade" }),
    linkedAt: timestamp("linked_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({ incidentEventIdx: uniqueIndex("incident_events_incident_event_idx").on(table.incidentId, table.eventId) }),
);

export const notifications = pgTable(
  "notifications",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    incidentId: uuid("incident_id").notNull().references(() => incidents.id, { onDelete: "cascade" }),
    channel: text("channel").notNull().default("telegram"),
    kind: text("kind").notNull(),
    severity: text("severity").notNull(),
    status: text("status").notNull().default("PENDING"),
    message: text("message").notNull(),
    deliveryAttempts: integer("delivery_attempts").notNull().default(0),
    lastError: text("last_error"),
    nextAttemptAt: timestamp("next_attempt_at", { withTimezone: true }),
    claimedAt: timestamp("claimed_at", { withTimezone: true }),
    claimToken: text("claim_token"),
    sentAt: timestamp("sent_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({ notificationKindIdx: uniqueIndex("notifications_incident_kind_idx").on(table.incidentId, table.kind) }),
);

export const opsAnalyses = pgTable(
  "ops_analyses",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    incidentId: uuid("incident_id").notNull().references(() => incidents.id, { onDelete: "cascade" }),
    status: text("status").notNull().default("PENDING"),
    summary: text("summary"),
    likelyCause: text("likely_cause"),
    confidence: integer("confidence_basis_points"),
    impact: text("impact"),
    recommendedActions: jsonb("recommended_actions").$type<{ capability: string; reason: string }[]>().notNull().default([]),
    provider: text("provider").notNull().default("vertex_ai"),
    model: text("model"),
    error: text("error"),
    attempts: integer("attempts").notNull().default(0),
    claimToken: text("claim_token"),
    claimedAt: timestamp("claimed_at", { withTimezone: true }),
    claimExpiresAt: timestamp("claim_expires_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    startedAt: timestamp("started_at", { withTimezone: true }),
    completedAt: timestamp("completed_at", { withTimezone: true }),
  },
  (table) => ({ incidentCurrentIdx: uniqueIndex("ops_analyses_incident_current_idx").on(table.incidentId) }),
);

export const commands = pgTable("commands", {
  id: uuid("id").defaultRandom().primaryKey(),
  commandId: text("command_id").notNull().unique(),
  projectId: uuid("project_id").notNull().references(() => projects.id),
  environment: text("environment").notNull(),
  capability: text("capability").notNull(),
  arguments: jsonb("arguments").notNull(),
  requestedAt: timestamp("requested_at", { withTimezone: true }).notNull(),
  validUntil: timestamp("valid_until", { withTimezone: true }).notNull(),
  status: text("status").notNull().default("REQUESTED"),
  deliveryMode: text("delivery_mode").notNull(),
  deliveryAttempts: integer("delivery_attempts").notNull().default(0),
  nextDeliveryAt: timestamp("next_delivery_at", { withTimezone: true }),
  claimToken: text("claim_token"),
  claimExpiresAt: timestamp("claim_expires_at", { withTimezone: true }),
  acknowledgedAt: timestamp("acknowledged_at", { withTimezone: true }),
  resultAt: timestamp("result_at", { withTimezone: true }),
  result: jsonb("result"),
  failureReason: text("failure_reason"),
  rejectionReason: text("rejection_reason"),
  requestedBy: text("requested_by").notNull().default("operator"),
  auditMetadata: jsonb("audit_metadata").$type<Record<string, string>>().notNull().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});
